"""reset riwayat dan inisialisasi tabel similarity_cache

Revision ID: 002a134cd6e5
Revises: 
Create Date: 2026-07-10 08:57:51.989371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002a134cd6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similarity_cache',
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('id_dokumen1', sa.Integer(), nullable=False),
    sa.Column('id_dokumen2', sa.Integer(), nullable=False),
    sa.Column('skor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokumen1'], ['dokumen_tugas.id_dokumen'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_dokumen2'], ['dokumen_tugas.id_dokumen'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_analisis.id_sesi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesi', 'id_dokumen1', 'id_dokumen2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_cache')
    # ### end Alembic commands ###
