"""inisialisasi semua tabel ERD

Revision ID: 0fc037f678bf
Revises: 
Create Date: 2026-06-11 18:45:27.217953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc037f678bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen_pengampu',
    sa.Column('id_dosen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_dosen'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sesi_analisis',
    sa.Column('id_sesi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dosen', sa.Integer(), nullable=False),
    sa.Column('nama_matkul', sa.String(length=100), nullable=False),
    sa.Column('kelas', sa.String(length=20), nullable=False),
    sa.Column('threshold_awal', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_file_terunggah', sa.Integer(), nullable=False),
    sa.Column('ukuran_terpakai_mb', sa.Float(), nullable=False),
    sa.Column('tanggal_buat', sa.DateTime(), nullable=False),
    sa.Column('tanggal_selesai', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('uploaded', 'analyzed', 'completed')", name='ck_status_sesi'),
    sa.CheckConstraint('total_file_terunggah <= 32', name='ck_max_file_per_sesi'),
    sa.ForeignKeyConstraint(['id_dosen'], ['dosen_pengampu.id_dosen'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_sesi')
    )
    op.create_table('dokumen_tugas',
    sa.Column('id_dokumen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('nama_file', sa.String(length=255), nullable=False),
    sa.Column('ukuran_file_mb', sa.Float(), nullable=False),
    sa.Column('path_penyimpanan', sa.String(length=500), nullable=False),
    sa.Column('teks_ekstraksi', sa.Text(), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_analisis.id_sesi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dokumen')
    )
    op.create_table('klaster',
    sa.Column('id_klaster', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('skor_tertinggi', sa.Float(), nullable=False),
    sa.Column('skor_terendah', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('skor_tertinggi >= skor_terendah', name='ck_skor_klaster'),
    sa.CheckConstraint('skor_tertinggi BETWEEN 0 AND 100', name='ck_skor_range'),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_analisis.id_sesi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_klaster')
    )
    op.create_table('laporan_evaluasi',
    sa.Column('id_laporan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('format_file', sa.String(length=10), nullable=False),
    sa.Column('path_file', sa.String(length=500), nullable=False),
    sa.Column('tanggal_ekspor', sa.DateTime(), nullable=False),
    sa.CheckConstraint("format_file IN ('pdf', 'xlsx')", name='ck_format_laporan'),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_analisis.id_sesi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_laporan')
    )
    op.create_table('detail_kemiripan',
    sa.Column('id_detail', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_klaster', sa.Integer(), nullable=False),
    sa.Column('id_dokumen1', sa.Integer(), nullable=False),
    sa.Column('id_dokumen2', sa.Integer(), nullable=False),
    sa.Column('persentase_kemiripan', sa.Float(), nullable=False),
    sa.Column('kalimat_highlight1', sa.Text(), nullable=True),
    sa.Column('kalimat_highlight2', sa.Text(), nullable=True),
    sa.CheckConstraint('id_dokumen1 <> id_dokumen2', name='ck_beda_dokumen'),
    sa.CheckConstraint('persentase_kemiripan BETWEEN 0 AND 100', name='ck_persentase_range'),
    sa.ForeignKeyConstraint(['id_dokumen1'], ['dokumen_tugas.id_dokumen'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_dokumen2'], ['dokumen_tugas.id_dokumen'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_klaster'], ['klaster.id_klaster'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detail')
    )
    op.create_table('dokumen_klaster',
    sa.Column('id_dokumen', sa.Integer(), nullable=False),
    sa.Column('id_klaster', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokumen'], ['dokumen_tugas.id_dokumen'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_klaster'], ['klaster.id_klaster'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_dokumen', 'id_klaster')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokumen_klaster')
    op.drop_table('detail_kemiripan')
    op.drop_table('laporan_evaluasi')
    op.drop_table('klaster')
    op.drop_table('dokumen_tugas')
    op.drop_table('sesi_analisis')
    op.drop_table('dosen_pengampu')
    # ### end Alembic commands ###
